---
- name: variables
  hosts: localhost
  vars_files:
    vars.yml
  tasks:
    - name: learning variables
      ansible.builtin.debug:
        msg: "Hi am {{name}} and I am from {{place}}. It's {{distance}} kms far away"