---
- name: Conditions
  hosts: localhost
  become: yes
  tasks:
  - name: Check user exits or not
    ansible.builtin.command: id roboshop
    register: user # user is a variable here
    ignore_errors: true
